### ISSUE TITLE
Implementation of selection list menu

### ISSUE THREAD

**Issue by ahmadbky** [ahbalbk/ezmenulib#3]
Sample code:
```rust
#[derive(Clone)]
enum Type {
  MIT,
  BSD,
  GPL
}

use ezmenulib::{SelectField, SelectMenu};
let selected = SelectMenu::from([
  SelectField::new("MIT", Type::MIT),
  SelectField::new("BSD", Type::BSD),
  SelectField::new("GPL", Type::GPL),
])
.default(0) // first select-field marked as default
.next_output()
.unwrap();
```
Supposing the user skipped the menu:
```rust
assert_eq!(selected, Type::MIT)
```

This is going to be really useful for sub-menu management, with select menus inside value-menus, etc.

- [X] Implemente `SelectMenu` and `SelectField` structs
- [X] Write docs
- [x] Add submenu management
- [x] Update README and lib.rs docs

**Comment by ahbalbk** [comment]
Updated to integrate binding function to be called right after the user selected the corresponding field:
```rust
fn bsd(e: &mut Stdout) -> MenuResult<()> {
  e.write_all(b"coucou this is from bsd\n").map_err(MenuError::from)
}

let selected = SelectMenu::from([
  SelectField::new("MIT", Type::MIT).bind(|_| Ok(println!("you selected MIT!!!"))),
  SelectField::new("BSD", Type::BSD).bind(bsd),
  // ...
]);
```
I'm not happy with the cumbersome function binding, it requires `&mut Stdout` as parameter and `MenuResult<()>` as return type even if we only use `println` macros, plus we need to map the error with `Result::map_err` to convert to a `MenuError`.

Moreover, I need to implement a way to give the `&Stdin` stream to the function if we want to reuse the initial input stream after selection, for submenu management for example.

**Comment by ahbalbk** [comment]
Updated to integrate `SelectMenu` inside `ValueMenu` to form a submenu:
```rust
#[derive(Clone)]
enum Type {
  MIT,
  GPL,
  BSD,
}

fn main() {
  let mut my_menu = ValueMenu::from([
    Field::Value(ValueField::from("Enter your name")),
    Field::Select(SelectMenu::from([
      SelectField::new("MIT", Type::MIT),
      SelectField::new("GPL", Type::GPL),
      SelectField::new("BSD", Type::BSD),
    ])
    .default(0)
    .title("Choose a license type"),
  ])
  .title("Configurate your license");
}
```
